timestamp = "2019-06-10T16:57:50.053948"
random_seed = 0
experiment = "at_risk2"
data_source = "/Users/jethromuller/masters/feature-engineering-aide/data_files/CSCFull.csv"
classifiers = [ "Naive Bayes", "Decision Tree", "Random Forest",]
metrics = [ "Accuracy", "F1 Score", "Matthew's Correlation Coefficient",]

[data]
selected_features = [ "EngBin", "AveSciBin", "AdMathAttempt",]
target = "CSCBin"
data_split_column = "Application Year"
holdout_split_condition = "2016"
true_values = [ "Yes", "Pass",]
false_values = [ "No", "Fail",]

[data.bool_type_features]
CSCBin = "bool"

[data.other_type_features]
EngBin = "category"
AveSciBin = "category"
AdMathAttempt = "category"
"Application Year" = "category"

[data.na_values]
EngBin = [ "*",]
AveSciBin = [ "*",]
CSCBin = [ "*",]
